# Generated by Django 5.2.1 on 2025-05-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='0', max_length=3)),
                ('bodytupe', models.CharField(default='standart', max_length=20)),
                ('personality', models.CharField(default='standart', max_length=20)),
                ('profession', models.CharField(default='standart', max_length=20)),
                ('health', models.CharField(default='standart', max_length=20)),
                ('hobby', models.CharField(default='standart', max_length=100)),
                ('phobia', models.CharField(default='standart', max_length=20)),
                ('largeInventory', models.CharField(default='standart', max_length=100)),
                ('backpack', models.CharField(default='standart', max_length=100)),
                ('additionalInformation', models.CharField(default='standart', max_length=100)),
                ('specialFeature', models.CharField(default='standart', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='GameRoom', max_length=20)),
                ('turn', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
