# Generated by Django 5.2.1 on 2025-05-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='standart', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='sex',
            field=models.CharField(default='standart', max_length=20),
        ),
    ]
