# Generated by Django 5.2.1 on 2025-05-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_name_card_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='bodytupe',
            new_name='bodytype',
        ),
    ]
